# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Mayur Srinivasan
tagline:          'Marketing Analytics & Data Science, Austin TX'
description:      'Musings on personal Data Science projects, travel, and everything there is to learn'
url:              linked.in.com/in/mayursrinivasan
baseurl:          /

author:
  name:           'Mayur Srinivasan'
  url:            https://twitter.com/xrinivasan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayursrinivasan
